# MCP Agent 設定ファイル

# データソース設定
data_sources:
  yahoo_finance:
    api_key: "${YAHOO_FINANCE_API_KEY}"
    endpoint: "https://yfapi.net/v6/finance/quote"
  
  news:
    google_news_api_key: "${GOOGLE_NEWS_API_KEY}"
    reuters_rss_url: "http://feeds.reuters.com/reuters/businessNews"


# LLM設定
llm:
  reasoner:
    model: "deeseek reasoner"
    api_key: "${DEEPSEEK_REASONER_API_KEY}"
    temperature: 0.7
    max_tokens: 2000
  chat:
    model: "deepseek chat" 
    api_key: "${DEEPSEEK_CHAT_API_KEY}"
    temperature: 0.5
    max_tokens: 1000
